Update aws.yml

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -17,10 +17,20 @@ jobs:
   build:
     name: Build
     runs-on: ubuntu-latest
-    if: ${{ github.event.inputs.helm_chart_changed != 'true' || github.run_number == 1 || !contains(github.event.head_commit.message, '[skip build]') }}
+    if: ${{ github.event.inputs.helm_chart_changed != 'true' && !contains(github.event.head_commit.message, '[skip build]') }}
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+
+      - name: Check for Helm chart changes
+        run: |
+          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
+          if echo "$CHANGED_FILES" | grep -q "^helm-chart/"; then
+            echo "Changes detected in helm-chart folder. Skipping build job."
+            exit 78 # Skip job with neutral exit code
+          else
+            echo "No changes detected in helm-chart folder. Proceeding with build job."
+          fi
 
       - name: Build
         run: |
@@ -30,7 +40,7 @@ jobs:
     name: Deploy
     runs-on: ubuntu-latest
     needs: build
-    if: always() && github.event.inputs.helm_chart_changed != 'true' && (github.run_number == 1 || github.event_name == 'push')
+    if: always() && github.event.inputs.helm_chart_changed != 'true'
     steps:
       - name: Checkout
         uses: actions/checkout@v4
